# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c-jCtZWkdt8hyExxPuqODjrgTIuFR6AZ
"""

student_name = input("Enter a name:")
math_marks = int(input("Enter maths marks:"))
science_marks = int(input("Enter  science marks:"))
english_marks = int(input("Enter english marks:"))
if math_marks < 0 or math_marks > 100 or science_marks < 0 or science_marks > 100 or english_marks < 0 or english_marks > 100:
  print("Invalid marks entered")
else:
  total = math_marks + science_marks + english_marks
  average = total / 3
  if math_marks < 40 or science_marks < 40 or english_marks < 40:
    result = "fail"
  else:
    result = "pass"
  if result == "pass":
      if average >= 90:
        grade = "A"
      elif average >= 75:
        grade = "B"
      elif average >= 60:
        grade = "C"
      else:
        grade = "D"
      print("Grade:", grade)
  print("Student name:", student_name)
  print("math marks:", math_marks)
  print("science marks:", science_marks)
  print("english marks:", english_marks)
  print("result:", result)
  print("Average:", average)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile game_score.py
# player_name = input("Enter player name:")
# games_played = int(input("Enter number of games played:"))
# total_score = int(input("Enter total score:"))
# average_score = total_score / games_played
# print("player name:", player_name)
# print("games played:", games_played)
# print("total score:", total_score)
# print("average score:", average_score)

